spring:
  autoconfigure:
    exclude: io.opentracing.contrib.spring.tracer.configuration.TracerAutoConfiguration
tootest-dotnet:
  host: localhost
  port: 4477




opentracing:
  spring:
    web:
      enabled: false

