logging:
  level:
    com:
      tootest:
        ch: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO
  file:
    path: /
    name: ch-user.log

tootest-dotnet:
  host: localhost
  port: 4477

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ThePassword
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ch_user
    username: springuser
  jpa:
    hibernate:
      ddl-auto: update

#spring.jpa.show-sql: true

server:
  port: 9211
