spring:
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:3306/ch_user
    username: ${DB_USERNAME}

tootest-dotnet:
  host: tootest-dotnet-service.tootest.svc.cluster.local
  port: 4477