tootest-dotnet:
  host: tootest-dotnet-service.tootest.svc.cluster.local
  port: 4477

logging:
  pattern:
    # Adds trace and span IDs to logs (when a trace is in progress)
    level: '%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n'
opentracing:
  spring:
    cloud:
      log:
        enabled: false
    web:
      enabled: true

jaeger:
  enabled: true
  service-name: ch-user
  endpoint: http://tracing-analysis-dc-sg-internal.aliyuncs.com/adapt_1l6gz6t0chu@395c9219c2340ca_1l6gz6t0chu@53df7ad2afe8301/api/traces