tootest-dotnet:
  host: tootest-dotnet-service.tootest.svc.cluster.local
  port: 4477

logging:
  pattern:
    console: '%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n'
opentracing:
  spring:
    cloud:
      log:
        enabled: false
occ:
  tracer:
    enabled: true
    service-name: ch_user