tootest-dotnet:
  host: tootest-dotnet-service.tootest.svc.cluster.local
  port: 4477

logging:
  pattern:
    # Adds trace and span IDs to logs (when a trace is in progress)
#    level: '%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n'
#    console: '%d{yyyy-MM-dd HH:mm:ss:SSS zzz} [%X{traceId}/%X{spanId}] [%t] %-5level %logger{36} - %msg%n'
    console: '%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n'
opentracing:
  spring:
    cloud:
      log:
        enabled: false
occ:
  tracer:
    enabled: true
    service-name: ch-user