apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-uf60e51dfzm6lzye1chhb"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
  name: user-service
  namespace: {NAMESPACE}
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
  - port: 9211
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
