apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {NAMESPACE}
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 9211
      targetPort: 9211
