apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
  - port: 9211
    protocol: TCP
    targetPort: 9211
  type: LoadBalancer
