# This is a basic workflow to help you get started with Actions

name: ACR Token

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  REGION_ID: cn-shanghai
  ACR_EE_INSTANCE_ID: cri-3fynibeigjxpi5o6
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Setup aliyun cli with credential
        uses: hughcube/aliyun-cli-action@1.0.1
        with:
          access-key-id: "${{ secrets.ALICLOUD_ACCESS_KEY }}"
          access-key-secret: "${{ secrets.ALICLOUD_SECRET_KEY }}"
          region: "${{ env.REGION_ID }}"
          
          
      - name: Aliyun help
        run: aliyun help
          
      - name: Get Token
        run: |
          SECRETJSON=$(aliyun cr GetAuthorizationToken --RegionId cn-shanghai --InstanceId cri-3fynibeigjxpi5o6)
          echo "JSON:$SECRETJSON"
          
