# This is a basic workflow to help you get started with Actions

name: ACR Token

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  REGION_ID: cn-shanghai
  ACR_EE_INSTANCE_ID: cri-3fynibeigjxpi5o6
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  acr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Setup aliyun cli with credential
        uses: hughcube/aliyun-cli-action@1.0.1
        with:
          access-key-id: "${{ secrets.ALICLOUD_ACCESS_KEY }}"
          access-key-secret: "${{ secrets.ALICLOUD_SECRET_KEY }}"
          region: "${{ env.REGION_ID }}"
          
          
      - name: Aliyun help
        run: aliyun help cr GetAuthorizationToken
          
      - name: Get Token
        run: |
          aliyun cr GetAuthorizationToken --InstanceId cri-3fynibeigjxpi5o6 --RegionId cn-shanghai 
          SECRETJSON=$(aliyun cr GetAuthorizationToken --RegionId cn-shanghai --InstanceId cri-3fynibeigjxpi5o6)
          echo "JSON:$SECRETJSON"
          
  updater-version:
#     needs: acr

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Fetch resources
        run: |
          TRACER_VERSION=$(curl -s https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-)
          echo "Verion is $TRACER_VERSION"
          echo $TRACER_VERSION > dd-trace-dotnet-version.txt

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: dd-trace-dotnet-version.txt
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
