# This is a basic workflow to help you get started with Actions

name: Update File

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Fetch resources
        run: |
          TRACER_VERSION=$(curl -s https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-)
          TRACER_VERSION_FROM_FILE=$(cat dd-trace-dotnet-version.txt)
          echo "Version from web: $TRACER_VERSION"
          echo "Version from file: $TRACER_VERSION_FROM_FILE"
          if [ "$TRACER_VERSION" = "$TRACER_VERSION_FROM_FILE" ]; then
            echo "The version from web and from the fole are equal. No need to update."
          else
              echo "The version from web and from the fole are equal. Need to update the version"
               echo $TRACER_VERSION > dd-trace-dotnet-version.txt
          fi
         

#       - name: Update resources
#         uses: test-room-7/action-update-file@v1
#         with:
#             file-path: dd-trace-dotnet-version.txt
#             commit-msg: Update resources
#             github-token: ${{ secrets.GITHUB_TOKEN }}
